services:
  app:
    image: maishanhub/edge-fast-image-queue:main
    container_name: aivro
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
    restart: unless-stopped
